### ISSUE TITLE
[WARN] :   Deprecation warning: moment().lang() is deprecated. Instead, use moment().localeData() to get the language configuration. Use moment().locale() to change languages.

### ISSUE THREAD

**Issue by stiffs** [viezel/napp.alloy.adapter.restsql#102]
SQLREST.js warnings:

[WARN] :   Deprecation warning: moment().lang() is deprecated. Instead, use moment().localeData() to get the language configuration. Use moment().locale() to change languages.

**Comment by RBAtkins0n** [comment]
Bump
