### ISSUE TITLE
Join Statement

### ISSUE THREAD

**Issue by terence1990** [viezel/napp.alloy.adapter.restsql#109]
Hey,

Thanks for this adapter it's awesome.

One issue I have is that I am often getting data from my rest server which has related tags. I can get models with relations with tags using urlparams just fine, and I can also store these tags locally as models themselves, my issue is that when using my app offline, I want to be able to still filter the existing models via their relationship with tags. 

For this I can create a relational table for the model tag relationship. I can save these relationships manually after fetch, but my issue is that when offline the method to get the desired models would be via a join statement.

Do you have plans to integrate join statements? And what is your recommendation for saving model tag relationships on fetch? This could be something built into the adapter too on read when fetching from server.

**Comment by viezel** [comment]
you will have to write those manually..

```javascript
{
    "sql": "SELECT ... FROM table1 JOIN table2 USING ( column1 ,... ) ..."
}
```

**Comment by terence1990** [comment]
Thanks!
