### ISSUE TITLE
Problem with  \ in data

### ISSUE THREAD

**Issue by gursel58** [viezel/napp.alloy.adapter.restsql#65]
I have just started using the RestSQL Adapter with a REST API Service (I have tested the REST API service using the Firefox  REST Easy addon and everything works in the service). I can get the  RestSQL talking to the REST Api service (authentication works) however I cant get them to exchange data.
When my app sends data up to the server I get a 400 error Required field is missing.
From what I understand of JSON it might be the \ before and after each  value. I saw another person who had the same issue but there was no information on how it was fixed or if it was the problem.

[REST API] REST METHOD: create
[DEBUG] :  [REST API] create options
[DEBUG] :  {
[DEBUG] :  "type": "POST",
[DEBUG] :  "headers": {
[DEBUG] :  "Authorization": "92cefcf92aeb80feb0f1c535d3afbffa",
[DEBUG] :  "Content-Type": "application/json"
[DEBUG] :  },
[DEBUG] :  "url": "http://192.168.1.94/imok/v1/index.php/items",
[DEBUG] :  "data": "{\"item\":\"asprin\",\"item_type\":\"Med\",\"client\":\"1\",\"createdatetime\":1420347238,\"reqdate\":\"\",\"quantity\":\"\",\"short_desc\":\"\",\"notes\":\"\",\"done\":0}"
[DEBUG] :  }

I am also not getting any data being received from the server.
Here is my model information:
config: {
		columns: {
		    "item": "string",
		    "item_id": "integer primary key autoincrement",
		    "item_type": "string",
		    "client": "string",
		    "createdatetime": "datetime",
		    "reqdate": "datetime",
		    "quantity" : "string",
		    "short_desc": "string",
		    "long_desc": "string",
		    "notes": "string",
		    "assignee": "string",
		    "done" : "integer",
		    "date_completed" : "datetime"
			},
//		"URL": Alloy.Globals.resturl,	
		"URL": "http://192.168.1.94/imok/v1/index.php/items",
        "debug": 1, //debug mode enabled
        "useStrictValidation":0, // validates each item if all columns are present
        
        "adapter" : {
            "type" : "sqlrest",
            "collection_name" : "items",
            "idAttribute" : "item_id",
            "addModifedToUrl": true,
            "lastModifiedColumn": "modified"
        },
        "headers": {
       	 "Authorization" : "92cefcf92aeb80feb0f1c535d3afbffa",
        },
        "eTagEnabled" : true,
        "initFetchWithLocalData" : false,
        // delete all models on fetch
        "deleteAllOnFetch": false,
        "returnErrorResponse" : true
	},
Is there something I missed ??

Thanks

**Comment by viezel** [comment]
invalid
