### ISSUE TITLE
Delete models that absent after fetch new dataset from server

### ISSUE THREAD

**Issue by falkolab** [viezel/napp.alloy.adapter.restsql#70]
Is there any other way to remove local entries are missing from the server response except send is_deleted from server? Apart from checking every local model is it exists in server dataset or not?

**Comment by viezel** [comment]
you can set "deleteAllOnFetch": true. That will delete all our models before the adapter will add the newly fetched.

**Comment by falkolab** [comment]
But in this case I will be forced to do full redraw ui.

**Comment by viezel** [comment]
yes of course.
