### ISSUE TITLE
Bugfix: fetch not work if not use urlparams and fill config.URLPARAMS

### ISSUE THREAD

**Issue by falkolab** [viezel/napp.alloy.adapter.restsql#71]
Look at https://github.com/falkolab/napp.alloy.adapter.restsql/commit/622a165139c8856cffbbae09c777c52035503fa5
Same in restapi.

**Comment by viezel** [comment]
Please make a PR.

**Comment by falkolab** [comment]
Sorry, I can't create new PR bypassing not approved another PR.
I do not familiar well enough with Git.

**Comment by viezel** [comment]
should be resolved in v. 0.3.0
