### ISSUE TITLE
Large list import advice

### ISSUE THREAD

**Issue by dottodot** [viezel/napp.alloy.adapter.restsql#77]
Just after a bit of advice as I'm trying to add a lot of items from a rest api and it takes a long time so just trying to get an idea if it should be quicker or not based on other people's experience.

There are 7000 items that I'm adding and retrieving in batches of 25 at a time, however this takes around 18 minutes to complete which seems way too long but I'm not sure if it's because I'm doing something wrong or if this is expected behaviour when detailing with this amount of data and saving it in a database.

The 1st 1000 loads in 38 seconds so if it continued like that it would be so bad as it would be less that 7 mins.

Anyway here's my code retrieves the items.

```
var loadAll = function(nextPage) {
    var pageNo = nextPage + 1 || 1;
    if (pageNo == 1) {
        $.loading.show();
    }
    guestlist.fetch({
        url : offlineUrl,
        urlparams : {
            user : user,
            token : token,
            page : pageNo
        },
        add : true,
        timeout : 60000,
        success : function(collection, response, options) {
            if (pageNo == pages) {
                $.loading.hide();
            } else {
                var progress = (collection.models.length / totalRecords) * 100;
                $.loading.progress(progress);
                loadAllGuests(pageNo);
            }
        },
        error : function(collection, response, options) {
            Ti.API.info(response);
            $.loading.hide();
        }
    });
};
```

**Comment by viezel** [comment]
have you tried to write in pure sql batch statements and compare?
It could be way faster to do it that way.

**Comment by dottodot** [comment]
OK I'll have a look into that. Could you just confirm that as long I insert into the right database and table my backbone collection will work as normal.

**Comment by viezel** [comment]
yep.. if you create the collection before you run your import, then alloy will create the table and use the migrations. e.g. Alloy.createCollection("myModal");

**Comment by dottodot** [comment]
That's amazing, it now does it in 4 minutes. Not sure if it could be any faster but certainly better than 18 minutes. Thanks for you help.

**Comment by viezel** [comment]
good to hear.. 
please post your batch script here, to help others.

**Comment by dottodot** [comment]
Of course yes, and I've now got it down to 1 min 15secs as before I was fetching the collection to get it's length for the progress but changing that to pure sql has made it even faster.

```
var loadAllGuests = function(nextPage) {
	var pageNo = nextPage + 1 || 1;
	if (pageNo == 1) {
		$.loading.show();
	}
	var getGuests = guestsFull(pageNo, function(resp, err) {
		var batch = resp.guestlist;
		var db = Ti.Database.open('_alloy_');
		db.execute('BEGIN');
		// begin the transaction
		for (var i = 0,
		    j = batch.length; i < j; i++) {
			var item = batch[i];
			db.execute('INSERT OR REPLACE INTO guestlist (first_name, last_name, quantity, serial_number, checked) VALUES (?, ?, ?, ?, ?)', item.first_name, item.last_name, item.quantity, item.serial_number, item.checked);
		}
		db.execute('COMMIT');
		if (pageNo == pages) {
			$.loading.hide();
			guestlist.fetch({
				localOnly : true,
				success : function(collection, response, options) {
					cloneGuests.add(guestlist.toJSON());
				}
			});
		} else {
			var rows = db.execute('SELECT serial_number FROM guestlist');
			var progress = (rows.rowCount / totalRecords) * 100;
			$.loading.progress(progress);
			loadAllGuests(pageNo);			
		}
		db.close();
	});
};
```
