### ISSUE TITLE
localOnly not working on save

### ISSUE THREAD

**Issue by lawjeremy** [viezel/napp.alloy.adapter.restsql#79]
the localOnly option works on fetch but not on save. is this intended behaviour or have I missed something?

**Comment by viezel** [comment]
it works on save, you just need to follow the guidelines from backbone where you pass an empty object in the first argument, then in the second, you use whatever property from this adapter. 

    model.save({}, {
        localOnly: true
    });

**Comment by lawjeremy** [comment]
That works, thanks for clarifying.

**Comment by arshavinho** [comment]
Hi,

thanks for the information @viezel.
I'm trying to use the function parentNode that i use to specify which child object i want to parse with the localOnly: true option. 
Do you have any idea how can i reach that ?
