### ISSUE TITLE
Could you give a bit more detail please

### ISSUE THREAD

**Issue by mawarnes** [viezel/napp.alloy.adapter.restsql#83]
I'm just trying to understand if this adapter will fully synchronise persistent storage between an app and a server. 
Will it successfully update the local storage on the device when there are later server changes? 
Will it also update the server if there are local changes that are more recent?
If both of the above cases are true, is it a fetch that will achieve this?
This adapter looks as if it will overwrite local data when running a fetch command...perhaps I'm not using it correctly?
If I do a fetch command, do I need to then save my collection...effectively doin a fetch to update my local storage, and a save to update the remote storage? (this is assuming there are changes on the server and different changes locally)

**Comment by Arialle** [comment]
Yes, this adapter will synchronize between the persisted database and the server JSON output.

Yes, the adapter will update the local storage on the device as long as you do not use "localOnly".

I have not tried getting the adapter to push changes to the server.

Model.save should be the function that pushes the data back to the server.

I am sure that I am not the right person to answer this, but you should save your model/collection after every change. Fetching data should only happen when you need a hard reset/synchronization of data.

**Comment by mawarnes** [comment]
hmmm, what I'm trying to do is fetch data which is a combination of local and remote updates.
I want to be able to add content offline, which is persisted locally, and each fecth will update the server, and return a set of any items that need to be applied locally
