### ISSUE TITLE
Use the latest version of "moment".

### ISSUE THREAD

**Issue by Arialle** [viezel/napp.alloy.adapter.restsql#86]
I am not sure where this issue should be but this library uses, moment = require('alloy/moment'), which is strangely not the latest version - using Titanium SDK 5.0.2.GA, Appcelerator 4.3.1.201509302304. I discovered this issue because I prefer my "lastModifiedDateFormat" to be "x", which is the Unix timestamp format.

**Comment by jvandijk** [comment]
@Arialle this is not an issue created by this library. You can go around this though by now, by using Alloy 1.7.30

That version comes with Moment.js 2.10
