### ISSUE TITLE
Get the request header data

### ISSUE THREAD

**Issue by thiagotalma** [viezel/napp.alloy.adapter.restsql#87]
Hello,

The API I consumer sends the paging data via the header.
How can I access these header data to know the total number of pages?

Example:

```
$ curl -i -H "Accept:application/json" "http://localhost/users"

HTTP/1.1 200 OK
...
X-Pagination-Total-Count: 1000
X-Pagination-Page-Count: 50
X-Pagination-Current-Page: 1
X-Pagination-Per-Page: 20
Link: <http://localhost/users?page=1>; rel=self, 
      <http://localhost/users?page=2>; rel=next, 
      <http://localhost/users?page=50>; rel=last
Transfer-Encoding: chunked
Content-Type: application/json; charset=UTF-8

[
    {
        "id": 1,
        ...
    },
    {
        "id": 2,
        ...
    },
    ...
]
```

**Comment by viezel** [comment]
that is not possible atm. you can create a PR for this?

**Comment by thiagotalma** [comment]
@viezel I could, but do not even know where to start... :smile: 

I am creating basic apps and do not have deep knowledge enough for this task.

**Comment by Arialle** [comment]
@thiagotalma To read the headers, you will can try HTTPClient.getResponseHeader(name). Regardless, do you know if you can make a "HEAD" request to the server? That would at least get you back the headers without having to get the response body.
