### ISSUE TITLE
Success function not called in v0.3.4 if returned data is null

### ISSUE THREAD

**Issue by jjcantillon** [viezel/napp.alloy.adapter.restsql#96]
Since upgrading to sqlrest v0.3.4 I have found when doing a fetch on a collection if my server returns a 200 response code with no data in my response object the success called function is not firing.

The error function also does not call.

This did not happen in v0.3.2

**Comment by mawarnes** [comment]
backbone injects code into the success function which adds/updates the collection as follows

	fetch: function(options) {
	options = options ? _.clone(options) : {};
	if (options.parse === undefined) options.parse = true;
	var collection = this;
	var success = options.success;
	options.success = function(resp, status, xhr) {
		collection[options.add ? 'add' : 'reset'](collection.parse(resp, xhr), options);
		if (success) success(collection, resp);
	};
	options.error = Backbone.wrapError(options.error, collection, options);
	return (this.sync || Backbone.sync).call(this, 'read', this, options);
	},

you say you have an empty response, what is the code in your success function?

**Comment by gimdongwoo** [comment]
If use model, it's a bug.

#104
